### ISSUE TITLE
BOT check - vysvetlenie

### ISSUE THREAD

**Issue by Lajcisvk** [municz/simple_rails_hw#4]
Ahoj, mohol by si mi prosim ta vysvetlit v com bol problem? Z toho co mi tam napisal bot nie som moc mudry

link: https://limitless-sands-6775.herokuapp.com/

BOT check
bot, results, yeaaahResults
Errors: 6. Warning: 3. 

Following errors found: 
* Can not save post. **(Neviem v com by mohol byt problem, ked tam bot dokazal postnut prispevok)**
* Can not find valid tags after deletion of post. **(Mazu sa iba tagy, ktore uz nemaju ani jeden post)**
* Could not find element with class .post-author class with author name. **(Meno autora je v `<div class="post-author">`)**
* Could not find element with class .post-title class with correct title. **(Titulok je v `<h4 class="post-title">`)**
* Could not find element with class .post-body class with post body. **(Text prispevku je v `<div class="post-body">`)**
* Invalid number of tag links (for filtering).. **(Nepodarilo sa mi zreprodukovat)**

Following warnings found: 
* Validate that you can save all kinds of posts with crazy inputs. **(Nepodarilo sa mi zreprodukovat)**
* Validate that you delete correct tags when a post is deleted." Validate creation of tags. **(Mazu sa iba tagy, ktore uz nemaju ani jeden post)**
* Validate, that tags have class "filter-by-tag". **(Odkazy na tagy su v `<a class="filter-by-tag"`)**

**Comment by Ryccoo** [comment]
Momentalne som mimo, ale napada ma aby si si skusil vstupy s tagmi napriklad "ahoj a , ako ssa     mas" ci ti to nepadne.

**Comment by Ryccoo** [comment]
napriklad toto ked dam ako tagy a ostatne dam validne tak to neulozi post a nevrati ziadnu chybu ":sdf sdf dsfsd fsd fds, ,  dsf sdf "

**Comment by Lajcisvk** [comment]
okej, dik fixnul som to, ale az budes mat cas potreboval by som vediet co je za problem s tymi element classami a pripadne dalsimi vecami, lebo ja tam oproti tvojej implementacii ziadny rozdiel nevidim
